#!/bin/bash
# © 2023. Triad National Security, LLC. All rights reserved.
# This program was produced under U.S. Government contract 89233218CNA000001 for Los Alamos
# National Laboratory (LANL), which is operated by Triad National Security, LLC for the U.S.
# Department of Energy/National Nuclear Security Administration. All rights in the program are
# reserved by Triad National Security, LLC, and the U.S. Department of Energy/National Nuclear
# Security Administration. The Government is granted for itself and others acting on its behalf a
# nonexclusive, paid-up, irrevocable worldwide license in this material to reproduce, prepare
# derivative works, distribute copies to the public, perform publicly and display publicly, and to permit
# others to do so.


xname=$(nid2xname $1)
if [[ -z "$xname" ]]; then
  echo "Do not understand $1" 1>&2
  exit 1
fi
conpod=$(kubectl -n services exec deploy/cray-console-operator -c cray-console-operator -- /app/get-node ${xname} | jq -r .podname)
if [ -z "$conpod" ]; then
  echo "Cannot find console pod for ${xname}" 1>&2
  exit 1
fi
exec kubectl -n services exec -it $conpod -c cray-console-node -- conman -j ${xname}
