#!/bin/bash
VERSION="%VERSION%-%RELEASE%"

for file in %LIBDIR%/*; do
    source $file
done

function main {
    export IMS_PUBLIC_KEY_ID=f25c56cb-fb05-498c-9427-582e0098fb9f
    case $1 in
        cfs*)
            shift
            cfs "$@"
            ;;
        cl*)
            shift
            cluster "$@"
            ;;
        con*)
            shift
            cfs "$@"
            ;;
        bo*)
            shift
            bos "$@"
            ;;
        gr*)
            shift
            group "$@"
            ;;
        im*)
            shift
            image "$@"
            ;;
        no*)
            shift
            node "$@"
            ;;
        re*)
            shift
            recipe "$@"
            ;;
        ve*)
            shift
            echo "shasta_wrapper $VERSION"
            ;;
        *)
            help_shasta
            ;;
    esac
}

function help_shasta {
  echo "USAGE: $0 [action]"
  echo "DESC: Intended to provide a more straitforward interface to the cray shasta environment. You can get more functionality via the direct 'cray' commands. However, they are very cumbersome to use"
  echo "ACTIONS:"
  echo "  bos : boot settings (session templates)"
  echo "  cluster : see cluster information"
  echo "  cfs : cfs ansible configuration options"
  echo "  group : group info and actions"
  echo "  image : image controls"
  echo "  node : node info and actions"
  echo "  recipe : recipes for building images"
  echo "  version : print software version"
}

main "$@"
