#!/bin/bash
VERSION="%VERSION%-%RELEASE%"

if [[ -z "$SHASTACMD_LIBDIR" ]]; then
    SHASTACMD_LIBDIR="%LIBDIR%"
fi
if [[ ! -d "$SHASTACMD_LIBDIR" ]]; then
    SHASTACMD_LIBDIR="$HOME/lib"
fi

for file in $SHASTACMD_LIBDIR/*; do
    source $file
done

function main {
    case $1 in
        cfs*)
            shift
            cfs "$@"
            ;;
        con*)
            shift
            cfs "$@"
            ;;
        bo*)
            shift
            bos "$@"
            ;;
        _edit_file)
            shift
            edit_file_nolock "$@"
            ;;
        fas)
            shift
            fas "$@"
            ;;
        gr*)
            shift
            group "$@"
            ;;
        im*)
            shift
            image "$@"
            ;;
        no*)
            shift
            node "$@"
            ;;
        power)
            shift
            power "$@"
            ;;
        rec*)
            shift
            recipe "$@"
            ;;
        regression*)
            shift
            regression "$@"
            ;;
        ve*)
            shift
            echo "shasta_wrapper $VERSION"
            ;;
        *)
            help_shasta
            ;;
    esac
}

function help_shasta {
  echo "USAGE: $0 [action]"
  echo "DESC: Intended to provide a more straitforward interface to the cray shasta environment. You can get more functionality via the direct 'cray' commands. However, they are very cumbersome to use"
  echo "ACTIONS:"
  echo "  bos : boot settings (session templates)"
  echo "  cfs : cfs ansible configuration options"
  echo "  fas : firmware flashing and validation"
  echo "  group : group info and actions"
  echo "  image : image controls"
  echo "  node : node info and actions"
  echo "  recipe : recipes for building images"
  echo "  power : controls power for components on the system"
  echo "  regression : run internal regression tests"
  echo "  version : print software version"
}

main "$@"
